name: 'Deploy Services'
description: 'Faz deploy dos serviços Docker Compose na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true
  project_path:
    description: 'Caminho do projeto na EC2'
    required: false
    default: '~/estacao-meteorologica'
  services:
    description: 'Serviços para fazer deploy (separados por vírgula)'
    required: false
    default: 'web consumer'

runs:
  using: 'composite'
  steps:
    - name: Deploy services
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          set -e
          
          INPUT_PATH="${{ inputs.project_path }}"
          if [ "${INPUT_PATH#~}" != "$INPUT_PATH" ]; then
            TRY_DIR="${INPUT_PATH/#\~/$HOME}"
          else
            TRY_DIR="$INPUT_PATH"
          fi
          
          if [ -d "$TRY_DIR" ]; then
            PROJECT_DIR="$TRY_DIR"
          elif [ -d "$HOME/estacao-meteorologica" ]; then
            PROJECT_DIR="$HOME/estacao-meteorologica"
          elif [ -d "/home/ec2-user/estacao-meteorologica" ]; then
            PROJECT_DIR="/home/ec2-user/estacao-meteorologica"
          elif [ -d "/opt/estacao-meteorologica" ]; then
            PROJECT_DIR="/opt/estacao-meteorologica"
          else
            echo "Erro: Diretório do projeto não encontrado"
            echo "Procurando em: $TRY_DIR, $HOME/estacao-meteorologica, /home/ec2-user/estacao-meteorologica, /opt/estacao-meteorologica"
            exit 1
          fi
          
          cd "$PROJECT_DIR" || exit 1
          echo "Trabalhando no diretório: $(pwd)"
          
          if [ ! -f "docker-compose.yaml" ] && [ ! -f "docker-compose.yml" ]; then
            echo "Erro: Arquivo docker-compose.yaml ou docker-compose.yml não encontrado em $(pwd)"
            ls -la
            exit 1
          fi
          
          docker-compose pull ${{ inputs.services }}
          docker-compose up -d --no-deps ${{ inputs.services }}
          docker-compose ps


