name: 'Setup AWS CLI'
description: 'Instala AWS CLI v2 na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup AWS CLI
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          if command -v aws &> /dev/null; then
            exit 0
          fi
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          sudo /tmp/aws/install
          rm -rf /tmp/aws /tmp/awscliv2.zip
