name: 'Copy Deploy Files'
description: 'Copia apenas arquivos necessários para o deploy (docker-compose.yaml, .env, rabbitmq/) na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true
  project_path:
    description: 'Caminho do projeto na EC2'
    required: false
    default: '~/estacao-meteorologica'

runs:
  using: 'composite'
  steps:
    - name: Copy deploy files
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          set -e
          
          INPUT_PATH="${{ inputs.project_path }}"
          EXPANDED_PATH=$(echo "$INPUT_PATH" | sed "s|^~|$HOME|")
          
          if [ -d "/home/ec2-user/estacao-meteorologica" ]; then
            PROJECT_DIR="/home/ec2-user/estacao-meteorologica"
          elif [ -d "/home/ubuntu/estacao-meteorologica" ]; then
            PROJECT_DIR="/home/ubuntu/estacao-meteorologica"
          elif [ -d "$EXPANDED_PATH" ]; then
            PROJECT_DIR="$EXPANDED_PATH"
          else
            PROJECT_DIR="$EXPANDED_PATH"
            mkdir -p "$PROJECT_DIR"
          fi
          
          echo "Diretório do projeto: $PROJECT_DIR"
          
          mkdir -p "$PROJECT_DIR/rabbitmq"
          mkdir -p "$PROJECT_DIR/letsencrypt"
          
          echo "✓ Diretórios criados"
          
          echo ""
          echo "Aguardando upload dos arquivos via GitHub Actions..."
          echo "Os arquivos serão copiados nas próximas etapas"

