name: 'Wait SSM Ready'
description: 'Aguarda EC2 estar pronta e SSM disponível'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true
  timeout:
    description: 'Timeout em segundos'
    required: false
    default: '300'

outputs:
  status:
    description: 'Status final (Online/Offline)'
    value: ${{ steps.wait.outputs.status }}

runs:
  using: 'composite'
  steps:
    - name: Wait for EC2 to be ready (SSM)
      id: wait
      shell: bash
      run: |
        TIMEOUT=${{ inputs.timeout }}
        ELAPSED=0
        
        while [ $ELAPSED -lt $TIMEOUT ]; do
          STATUS=$(aws ssm describe-instance-information \
            --filters "Key=InstanceIds,Values=${{ inputs.instance_id }}" \
            --query 'InstanceInformationList[0].PingStatus' \
            --output text 2>/dev/null || echo "Offline")
          
          if [ "$STATUS" = "Online" ]; then
            echo "status=Online" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          sleep 10
          ELAPSED=$((ELAPSED + 10))
        done
        
        echo "status=Offline" >> $GITHUB_OUTPUT
        exit 1

