name: 'Setup Docker'
description: 'Instala Docker na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Docker
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          set -e
          if command -v docker &> /dev/null; then
            exit 0
          fi
          . /etc/os-release
          if [ "$ID" = "amzn" ] || [ "$ID" = "rhel" ] || [ "$ID" = "centos" ]; then
            sudo yum update -y && sudo yum install -y docker
            sudo systemctl start docker && sudo systemctl enable docker
            sudo usermod -aG docker $USER || true
          elif [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ]; then
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/$ID/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo usermod -aG docker $USER || true
          fi
