name: 'Setup Project'
description: 'Prepara diretório do projeto na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true
  project_path:
    description: 'Caminho do projeto'
    required: false
    default: '~/estacao-meteorologica'

runs:
  using: 'composite'
  steps:
    - name: Setup Project Directory
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          mkdir -p ${{ inputs.project_path }}
          cd ${{ inputs.project_path }} || cd ~/estacao-meteorologica || cd /home/ec2-user/estacao-meteorologica || cd /opt/estacao-meteorologica