name: 'Setup Project'
description: 'Prepara diretório do projeto na EC2 via SSM'

inputs:
  instance_id:
    description: 'Instance ID da EC2'
    required: true
  project_path:
    description: 'Caminho do projeto'
    required: false
    default: '~/estacao-meteorologica'

runs:
  using: 'composite'
  steps:
    - name: Setup Project Directory
      uses: ./.github/actions/run-ssm-command
      with:
        instance_id: ${{ inputs.instance_id }}
        command: |
          set -e
          
          PROJECT_PATH="${{ inputs.project_path }}"
          if [ "${PROJECT_PATH#~}" != "$PROJECT_PATH" ]; then
            PROJECT_PATH="${PROJECT_PATH/#\~/$HOME}"
          fi
          
          echo "Criando diretório do projeto em: $PROJECT_PATH"
          mkdir -p "$PROJECT_PATH"
          cd "$PROJECT_PATH"
          echo "Diretório criado: $(pwd)"