# Generated by Django 4.2 on 2025-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('luminosidade', models.FloatField()),
                ('qualidade_ar', models.FloatField()),
                ('chuva', models.FloatField()),
            ],
        ),
    ]
