# Generated by Django 4.2 on 2025-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosensor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosensor',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dadosensor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
