# Generated by Django 4.2 on 2025-11-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensores", "0002_dadosensor_latitude_dadosensor_localizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dadosensor",
            name="altitude_m",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dadosensor",
            name="pressao_hpa",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dadosensor",
            name="temperatura_bmp",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dadosensor",
            name="umidade_solo_pct",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dadosensor",
            name="vento_kmh",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="dadosensor",
            name="vento_ms",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
