name: Start EC2

on:
  schedule:
    - cron: '0 22 * * 1-5'
    - cron: '0 3 * * 6,0'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  start-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::914256152987:role/GitHubActionsRole
          role-session-name: pi5-start-ec2-instance

      - name: Start EC2 Instance
        run: aws ec2 start-instances --instance-ids ${{ secrets.PI5_EC2_INSTANCE_ID }}